### PR TITLE
fix: Resolve panic in `Decoder.Skip()` with corrupt message

### LINKED ISSUE #158: .Decode() indexing panic
## Title

.Decode() method panics instead of error
## Version

v0.30.0
## Description

In some cases the .Decode() method which calls Skip() method here -> https://github.com/CrowdStrike/csproto/blob/main/decoder.go#L903, panics if indexing is out of range. Can we add a check here to fail/error rather than panic

### PR DESCRIPTION
**Pull request by dylan-bourque**
This PR resolves a panic when trying to decode a corrupted message, specifically one where the encoded length of a string field is >2GB.

I also added a new `ParseAnnotatedHex()` function in a new `prototest` package.  This function can be used to convert a string containing a "commented" hexadecimal representation of an encoded Protobuf message into binary, which is useful for managing test data in a more human-readable form.  See the godoc comments on the function for more details.

Finally, I updated `.golangci.yml` to resolve some config deprecations, which led to having to update some test code that was now generating linter warnings.

Fixes #158

### CODE REVIEW

File: decoder.go [hunk 1]
```diff
@@ -183,17 +185,14 @@ func (d *Decoder) DecodeBytes() ([]byte, error) {
 	if d.offset >= len(d.p) {
 		return nil, io.ErrUnexpectedEOF
 	}
+
 	l, n, err := DecodeVarint(d.p[d.offset:])
+	err = d.validateFieldLen(l, n, err)
```
Comment (wmorgan6796) [inline decoder.go:190]: nit, you could inline this with the error check which would be consistent with that you've done elsewhere
```suggestion
	if err = d.validateFieldLen(l, n, err); err != nil {
```

File: decoder.go [hunk 2]
```diff
@@ -960,6 +957,24 @@ func (d *Decoder) Skip(tag int, wt WireType) ([]byte, error) {
...
 
+// validateFieldLen is a helper to DRY up checking the result of DecodeVarint() when used to read the
+// length of a length-delimited field.
+func (d *Decoder) validateFieldLen(l uint64, n int, err error) error {
+	// length-delimited fields cannot contain more than 2GB
+	const maxFieldLen = math.MaxInt32
+
+	switch {
+	case err != nil:
+		return fmt.Errorf("invalid data at byte %d: %w", d.offset, err)
```
Comment (wmorgan6796) [inline decoder.go:968]: It seems odd to me that an error check for an error that occurs outside this function is checked here. Is this done for a performance reason or just to prevent another if err != nil...

**Review by wmorgan6796 — APPROVED** [review]
Approved with 1 nit and a question.

File: decoder.go (hunk 1 above)
Comment (dylan-bourque) [reply decoder.go:190]: Fair.  I think I actually wrote this one first and inlined the others.

File: decoder.go (hunk 2 above)
Comment (dylan-bourque) [reply decoder.go:968]: This is DRY'ing up checking the 3 failure cases for `DecodeVarint()`when the value is the length of a length-delimited field.  I'll admit it's a bit odd, but it felt less odd than checking 1 of the 3 failure cases at each call site.

File: decoder.go (hunk 1 above)
Comment (dylan-bourque) [reply decoder.go]: Updated

File: decoder.go (hunk 2 above)
Comment (dylan-bourque) [reply decoder.go]: I ended up removing the `validateFieldLen()` helper.  It did feel just a bit too unidiomatic for the benefit it was providing
